"""empty message

Revision ID: 0bce175b56db
Revises: 
Create Date: 2017-08-15 14:34:14.467137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bce175b56db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('flight_id', sa.String(length=10), nullable=True),
    sa.Column('insurance_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['insurance_id'], ['insurances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.add_column(u'DB_flight_data', sa.Column('Flight_time', sa.Integer(), nullable=True))
    op.add_column(u'DB_flight_data', sa.Column('Latitude', sa.Float(), nullable=True))
    op.add_column(u'DB_flight_data', sa.Column('Longitude', sa.Float(), nullable=True))
    op.add_column(u'DB_flight_data', sa.Column('standard_Departure', sa.Time(), nullable=True))
    op.add_column(u'DB_flight_data', sa.Column('standard_arrival', sa.Time(), nullable=True))
    op.add_column(u'DB_flight_data', sa.Column('time_block', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'DB_flight_data', 'time_block')
    op.drop_column(u'DB_flight_data', 'standard_arrival')
    op.drop_column(u'DB_flight_data', 'standard_Departure')
    op.drop_column(u'DB_flight_data', 'Longitude')
    op.drop_column(u'DB_flight_data', 'Latitude')
    op.drop_column(u'DB_flight_data', 'Flight_time')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
