"""empty message

Revision ID: 2a8337d674e1
Revises: 5e2e0b54d416
Create Date: 2017-09-03 17:43:41.331543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8337d674e1'
down_revision = '5e2e0b54d416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timestamp', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timestamp')
    # ### end Alembic commands ###
