"""empty message

Revision ID: 51558d62210f
Revises: 
Create Date: 2017-06-13 16:05:03.798458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51558d62210f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_records',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('arrival_airport', sa.String(length=20), nullable=True),
    sa.Column('departure_airport', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_records_arrival_airport'), 'flight_records', ['arrival_airport'], unique=False)
    op.create_index(op.f('ix_flight_records_departure_airport'), 'flight_records', ['departure_airport'], unique=False)
    op.create_table('insurance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('money_paid', sa.Float(), nullable=True),
    sa.Column('interest', sa.Float(), nullable=True),
    sa.Column('flight_date', sa.Date(), nullable=True),
    sa.Column('account', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('flight_date', sa.Date(), nullable=True),
    sa.Column('flight_no', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['flight_no'], ['flight_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_records_email'), 'user_records', ['email'], unique=True)
    op.create_index(op.f('ix_user_records_first_name'), 'user_records', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_records_last_name'), 'user_records', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_records_username'), 'user_records', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_records_username'), table_name='user_records')
    op.drop_index(op.f('ix_user_records_last_name'), table_name='user_records')
    op.drop_index(op.f('ix_user_records_first_name'), table_name='user_records')
    op.drop_index(op.f('ix_user_records_email'), table_name='user_records')
    op.drop_table('user_records')
    op.drop_table('insurance_records')
    op.drop_index(op.f('ix_flight_records_departure_airport'), table_name='flight_records')
    op.drop_index(op.f('ix_flight_records_arrival_airport'), table_name='flight_records')
    op.drop_table('flight_records')
    # ### end Alembic commands ###
