"""empty message

Revision ID: 5e2e0b54d416
Revises: cf6ce91307da
Create Date: 2017-09-03 17:30:16.611091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2e0b54d416'
down_revision = 'cf6ce91307da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('blockchain_receipt', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('insurance_id', sa.String(length=25), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'insurance_id')
    op.drop_column('users', 'blockchain_receipt')
    # ### end Alembic commands ###
