"""empty message

Revision ID: d8c35e38d913
Revises: 6283e08dff86
Create Date: 2017-06-13 02:30:27.742154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8c35e38d913'
down_revision = '6283e08dff86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_data',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('arrival_airport', sa.String(length=20), nullable=True),
    sa.Column('departure_airport', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_data_arrival_airport'), 'flight_data', ['arrival_airport'], unique=False)
    op.create_index(op.f('ix_flight_data_departure_airport'), 'flight_data', ['departure_airport'], unique=False)
    op.create_table('insurance_records',
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('money_paid', sa.Float(), nullable=True),
    sa.Column('interest1', sa.Float(), nullable=True),
    sa.Column('interest2', sa.Float(), nullable=True),
    sa.Column('interest3', sa.Float(), nullable=True),
    sa.Column('flight_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('flight_date', sa.Date(), nullable=True),
    sa.Column('flight_no', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['flight_no'], ['flight_data.id'], ),
    sa.ForeignKeyConstraint(['username'], ['insurance_records.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_data_email'), 'user_data', ['email'], unique=True)
    op.create_index(op.f('ix_user_data_first_name'), 'user_data', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_data_last_name'), 'user_data', ['last_name'], unique=False)
    op.drop_table('departments')
    op.drop_table('roles')
    op.drop_table('employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], [u'departments.id'], name=u'employees_ibfk_1'),
    sa.ForeignKeyConstraint(['role_id'], [u'roles.id'], name=u'employees_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('departments',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_index(op.f('ix_user_data_last_name'), table_name='user_data')
    op.drop_index(op.f('ix_user_data_first_name'), table_name='user_data')
    op.drop_index(op.f('ix_user_data_email'), table_name='user_data')
    op.drop_table('user_data')
    op.drop_table('insurance_records')
    op.drop_index(op.f('ix_flight_data_departure_airport'), table_name='flight_data')
    op.drop_index(op.f('ix_flight_data_arrival_airport'), table_name='flight_data')
    op.drop_table('flight_data')
    # ### end Alembic commands ###
